version: '3'

services:
  arserver:
    image: arcor2/arcor2_arserver:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: arserver
    depends_on:
      - project
      - build
      - execution
      # - mocks
    ports:
      - "6789:6789"
      - "6780:8888"
    networks:
          - testitoff-robot-network
    environment:
      - REST_ROBOT_SERVICE_URL=http://testitoff-robot-webapi:13000 
      - SEARCH_SERVICE_URL=http://testitoff-search-webapi:12000
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:10000
      - ARCOR2_SCENE_SERVICE_URL=http://testitoff-scene-webapi:15000
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_BUILD_URL=http://build:5008
      - BARCODE_SERVICE_URL=http://testitoff-barcode-webapi:14000
      - STATISTIC_SERVICE_URL=http://testitoff-statistic-webapi:16000
      - ARCOR2_DATA_PATH=/root/data
      - INTERACTION_SERVICE_URL=http://testitoff-interaction-webapi:17000

  build:
    image: arcor2/arcor2_build:${ARCOR2_BUILD_VERSION:?ARCOR2_BUILD_VERSION env variable not set}
    container_name: build
    environment:
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:10000
    ports:
      - "5008:5008"
    networks:           
      - testitoff-robot-network
  execution:
    image: arcor2/arcor2_execution:${ARCOR2_EXECUTION_VERSION:?ARCOR2_EXECUTION_VERSION env variable not set}
    container_name: execution
    networks:
          - testitoff-robot-network
    environment:
      - ARCOR2_SCENE_SERVICE_URL=http://testitoff-scene-webapi:15000
      - ARCOR2_PROJECT_PATH=/root/project
    volumes:
        - execution:/root/project

  execution-proxy:
    image: arcor2/arcor2_execution_proxy:${ARCOR2_EXECUTION_VERSION:?ARCOR2_EXECUTION_VERSION env variable not set}
    container_name: execution-proxy    
    environment:
      - ARCOR2_EXECUTION_PROXY_DB_PATH=/root/tokens
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_PROJECT_PATH=/root/project
    volumes:
      - execution-proxy:/root/tokens
      - execution:/root/project
    ports:
      - "5009:5009"
    networks:
      - testitoff-robot-network          
    depends_on:
      - execution

  testitoff-scene-webapi:
      image: registry.gitlab.com/kinalisoft/test-it-off/scene:0.2.0
      container_name: "testitoff-scene"
      restart: always
      ports:
          - "15000:15000"
      networks:
          - testitoff-robot-network
      environment:
          - ROBOTSYSTEM_SERVICE_URL=http://testitoff-robotsystem-webapi:14000  

  testitoff-robotsystem-webapi:
      image: registry.gitlab.com/kinalisoft/test-it-off/robotsystem/simulator:0.2.1
      container_name: "testitoff-robotsystem-webapi"
      expose:
          - "14000"
      environment:
          - MONGODB_URL=testitoff-robotsystem-mongodb:27017
      ports:
        - "14000:14000"
      restart: always
      networks:
        - testitoff-robot-network
  testitoff-robotsystem-mongodb:
      image: mongo:4.2.0-bionic
      container_name: "testitoff-robotsystem-mongodb"
      restart: always
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
      volumes:
          - testitoff-robotsystem-mongodb:/data/db
      networks:
          - testitoff-robot-network
      expose:
          - "27017"
      ports:
          - "14017:27017"  

  project:
    image: registry.gitlab.com/kinalisoft/test-it-off/project:0.4.0
    container_name: "project"
    ports:
      - "10000-10001:10000-10001"
    environment:
      MONGODB_URL: mongodb:27017
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - testitoff-robot-network

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"
    networks:
      - testitoff-robot-network



volumes:
  mongodb:   
  execution-proxy:
  execution:
  testitoff-robotsystem-mongodb:

networks:
  testitoff-robot-network: 

